### ISSUE TITLE
Implement toFloat

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#273] opened 2020-06-27 17:57 UTC
Following [@mhagmajer's comment](https://github.com/xFAANG/askql/issues/269#issuecomment-650568501), a `toFloat` resource is needed, which converts the argument to float.

Hint for new contributors:
Check how `toInt` is implemented and write `toFloat` in a similar manner.

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our [Discord Community](https://discord.gg/pYdzypH) and let us know there. We will be very happy to help you start! :)

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by engylemure** [comment] 2020-07-01 04:44
@mhagmajer and @czerwinskilukasz1  Considering that the JS does not have an internal difference between integer and float since they both are [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) this seems to be tricky, are you guys thinking about implementing wrappers for more explicitly handling the differences between the values considering casts?

**Comment by czerwinskilukasz1** [comment] 2020-07-10 11:07
Hi @engylemure , great question and sorry for taking a bit longer to reply, I was busy with solving tickets, haha :) 
We are going to implement type checking (per https://github.com/xFAANG/askql/issues/45) and `float` and `int` are separate types.
We already have them listed [in our grammar](https://github.com/xFAANG/askql/blob/master/src/askscript/parser/askscript.grammar.pegjs#L245) as well as other built-in types.
Does this answer your question?

**Comment by jamesd35** [comment] 2020-08-03 23:19
Hi can I work on this feature?

**Comment by czerwinskilukasz1** [comment] 2020-08-03 23:27
Sure, go ahead @jamesd35 !

**Comment by jamesd35** [comment] 2020-08-04 17:22
Hi, I have a question on the intended behavior for integers passed into ToFloat.

Based on the float definition it seems that any integers will not be validated
`export const float = type<Type<number>, Type<number>>(number, {
  name: 'float',
  validate: (value): value is number => value % 1 !== 0,
});`

Currently if I pass in an integer, it returns it as an int
`toFloat(4)
int ask(call(get('toFloat'),4))
4`

Is this correct or should it return a float such as 4.0?

**Comment by czerwinskilukasz1** [comment] 2020-08-04 17:48
Good catch, jamesd35.  Since @mhagmajer wrote the types and validators, let's wait for his reply.

**Comment by mhagmajer** [comment] 2020-08-04 17:54
JavaScript wont differentiate between `4.0` and `4` because it treats it as the same data type. We do, however, with CLI written in JavaScript it's difficult to tell the difference

**Comment by jamesd35** [comment] 2020-08-04 18:16
In that case, should the correct behavior to be to return the integer, but as a float type?

**Comment by czerwinskilukasz1** [comment] 2020-08-10 14:52
> In that case, should the correct behavior be to return the integer, but as a float type?

@mhagmajer , would you have a while to reply?

**Comment by jamesd35** [comment] 2020-08-17 20:21
Just wondering if anyone had a chance to look at my pull request?

**Comment by mhagmajer** [comment] 2020-09-11 12:01
@jamesd35 merged already :)

**Closed by mhagmajer** 2020-09-11 12:01 UTC
Labels: AskVM, enhancement, first-timers-only, good first issue, help wanted, type:resources
