### ISSUE TITLE
`npm test` does not run `.test.ask` test files

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#66] opened 2020-06-05 19:34 UTC
How to reproduce:
1. Open a *.test.ask file, e.g. src/askscript/__tests__/00-documentation-examples/documentation01-complete_example.test.ask
2. Write an untrue expect().toBe() statement, e.g.: expect(2 + 2):toBe(5)
3. Run `npm test`.

Expected: `npm test` fails with an error.
Actual: `npm test` succeeds with no error.  
Note that also running `npm test src/askscript/__tests__/00-documentation-examples/documentation01-complete_example.test.ask` succeeds with a 'todo' mark:

 PASS   test  src/askscript/__tests__/00-documentation-examples/documentation01-complete_example.test.ask
  ✓ starts
  ✓ compiles
  ✎ todo computes

**Comment by mhagmajer** [comment] 2020-06-21 20:10
Closing as a duplicate of https://github.com/xFAANG/askql/issues/154

**Closed by mhagmajer** 2020-06-21 20:10 UTC
Labels: CI/TDD/DevOps, bug, duplicate
